### ISSUE TITLE
Localization (l10n)

### ISSUE THREAD

**Issue by miresk** [Ziggeo/angular-ziggeo-demo#1]
Hey,

I really like the ziggeo API and this demo, but is there a way to make localization work with angular components (i.e recorder) ?
https://ziggeo.com/docs/sdks/javascript/browser-integration/localization
I can get an instance of the recorder, but don't know how to access for example ZiggeoApi.V2.Locale.mainLocale.all(); as described in documentation. Thanks

**Comment by sambua** [comment]
Hello @miresk ,

Thanks a lot for your feedback and using ziggeo API 👍 

We have upgrade package to version `angular-ziggeo@0.1.2`, please upgrade from your side and add option `l10n` (Example: `[options]="{ ..., l10n: 'de', ...}"`)

Have a good day and coding :)

**Comment by sambua** [comment]
Localization option was added
